name: fierroscocharcas
description: "Aplicación móvil Fierros Cocharcas con login, productos, carrito y perfil usando Firebase Realtime Database."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  firebase_database: ^11.1.3
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/banners/
    - lib/assets/marcas/
    - lib/assets/productos/
