// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGJtSdL8IY0qId3bG-ALfaqfSWkZ4CyQ',
    appId: '1:946820706303:web:9c2d7502e08f3ed27581ca',
    messagingSenderId: '946820706303',
    projectId: 'dam-fierroscocharcas-grupal',
    authDomain: 'dam-fierroscocharcas-grupal.firebaseapp.com',
    storageBucket: 'dam-fierroscocharcas-grupal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAel1bfMqTF2c4-Sm58H_M8g4p2VzQ9D3I',
    appId: '1:946820706303:android:8641f0e1aa28a8387581ca',
    messagingSenderId: '946820706303',
    projectId: 'dam-fierroscocharcas-grupal',
    storageBucket: 'dam-fierroscocharcas-grupal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3CZGHBBC-hnECvkiHS5oIxjVsaBOv2g',
    appId: '1:946820706303:ios:9263149e6b5b9e847581ca',
    messagingSenderId: '946820706303',
    projectId: 'dam-fierroscocharcas-grupal',
    storageBucket: 'dam-fierroscocharcas-grupal.firebasestorage.app',
    iosBundleId: 'com.example.fierroscocharcas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb3CZGHBBC-hnECvkiHS5oIxjVsaBOv2g',
    appId: '1:946820706303:ios:9263149e6b5b9e847581ca',
    messagingSenderId: '946820706303',
    projectId: 'dam-fierroscocharcas-grupal',
    storageBucket: 'dam-fierroscocharcas-grupal.firebasestorage.app',
    iosBundleId: 'com.example.fierroscocharcas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGJtSdL8IY0qId3bG-ALfaqfSWkZ4CyQ',
    appId: '1:946820706303:web:5619523c81efa0cb7581ca',
    messagingSenderId: '946820706303',
    projectId: 'dam-fierroscocharcas-grupal',
    authDomain: 'dam-fierroscocharcas-grupal.firebaseapp.com',
    storageBucket: 'dam-fierroscocharcas-grupal.firebasestorage.app',
  );
}
